default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: backoffice_development

test:
  <<: *default
  database: backoffice_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: backoffice_production
  username: backoffice
  password: <%= ENV['BACKOFFICE_DATABASE_PASSWORD'] %>
