default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: backoffice_development

test:
  <<: *default
  database: backoffice_test

production:
  adapter: postgresql
  host: dpg-cghremak728s1bq4jjjg-a.oregon-postgres.render.com
  port: 5432
  database: backoffice_fg23
  username: backoffice_fg23_user
  password: 1NxxhTY0z0nqIH5tuTyRIeWzZYXZ0ouc
