default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: backoffice_development

test:
  <<: *default
  database: backoffice_test

production:
  adapter: postgresql
  host: dpg-cghrl782qv2772nmanpg-a
  port: 5432
  database: postgres_hxef
  username: postgres_hxef_user
  password: e6L7qm0AneQPrUFJntELQOiikBedeziC
